StudentInformationSystem/StudentInformationSystem/Controllers/CourseController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32.SafeHandles;
using StudentInformationSystem.Services.Contracts;
using StudentInformationSystem.Web.ViewModels.Course;

namespace StudentInformationSystem.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        private readonly ITeacherService teacherService;
        private readonly ICourseService courseService;
        private readonly ISpecialtyService specialtyService;
        private readonly IStudentService studentService;

        public CourseController(ICourseService courseService, ITeacherService teacherService, ISpecialtyService specialtyService, IStudentService studentService)
        {
            this.studentService = studentService;
            this.specialtyService = specialtyService;
            this.courseService = courseService;
            this.teacherService = teacherService;
        }

        [Authorize(Roles = "Admin,Student")]
        public async Task<IActionResult> ShowMine()
        {
            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var courses = await this.courseService.GetStudentClassesAsync(userId);

            return View(courses);
        }

        [Authorize(Roles = "Admin,Student")]
        public async Task<IActionResult> Schedule()
        {
            string userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var courses = await this.courseService.GetStudentScheduleAsync(userId);

            return View(courses);
        }

        public async Task<IActionResult> Details(int id)
        {
            var courseDetails = await this.courseService.GetCourseDetailsAsync(id);

            return View(courseDetails);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var course = await this.courseService.GetCourseForEditAsync(id);
            course.Teachers = await this.teacherService.GetTeachersForListItemAsync();
            course.Specialties = await this.specialtyService.GetSpecialtiesForListItemAsync();

            return View(course);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, EditCourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "You should fill all the fields";
                model.Teachers = await this.teacherService.GetTeachersForListItemAsync();
                model.Specialties = await this.specialtyService.GetSpecialtiesForListItemAsync();
                return View(model);
            }

            if (model.Start.Hour >= model.End.Hour || model.End.Hour < model.Start.Hour)
            {
                TempData["ErrorMessage"] = "You should put valid start and end times";
                model.Teachers = await this.teacherService.GetTeachersForListItemAsync();
                model.Specialties = await this.specialtyService.GetSpecialtiesForListItemAsync();
                return View(model);
            }


            await this.courseService.EditCourseAsync(id, model);

            return RedirectToAction("Details", new { id = id });
        }

        public async Task<IActionResult> ShowAll()
        {
            var courses = await this.courseService.GetAllCoursesAsync();

            return View(courses);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var course = new EditCourseViewModel();
            course.Teachers = await this.teacherService.GetTeachersForListItemAsync();
            course.Specialties = await this.specialtyService.GetSpecialtiesForListItemAsync();

            return View(course);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Add(EditCourseViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "You should fill all the fields";
                model.Teachers = await this.teacherService.GetTeachersForListItemAsync();
                model.Specialties = await this.specialtyService.GetSpecialtiesForListItemAsync();
                return View(model);
            }

            if (model.Start.Hour >= model.End.Hour || model.End.Hour < model.Start.Hour)
            {
                TempData["ErrorMessage"] = "You should put valid start and end times";
                model.Teachers = await this.teacherService.GetTeachersForListItemAsync();
                model.Specialties = await this.specialtyService.GetSpecialtiesForListItemAsync();
                return View(model);
            }

            await this.courseService.CreateCourseAsync(model);

            return RedirectToAction("ShowAll");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            await this.courseService.DeleteCourseAsync(id);

            return RedirectToAction("ShowAll");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddStudents(int id)
        {
            var students = await this.courseService.FetchStudentsForCourseAsync(id);
            ViewBag.CourseId = id;
            return View(students);
        }

        [Authorize(Roles = "Admin,Teacher")]
        [HttpPost]
        public async Task<IActionResult> AddStudentsToCourse(int courseId, string studentEmail)
        {
            var studentId = await this.studentService.GetStudentIdByEmail(studentEmail);

            try
            {
                await this.courseService.EnrollStudentAsync(courseId, studentId);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = e.Message;
                return RedirectToAction("AddStudents", new { id = courseId });
            }

            return RedirectToAction("Details", new { id = courseId });
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveStudent(int courseId, string studentId)
        {
            await this.courseService.UnenrollStudentAsync(courseId, studentId);

            return RedirectToAction("Details", new { id = courseId });
        }

        public async Task<IActionResult> AddStudentsToCourse(int id)
        {
            ViewData["CourseId"] = id;
            return View();
        }

        public async Task<IActionResult> EditGrade(int courseId, string studentId)
        {
            await this.courseService.ResetGrade(courseId, studentId);
            return RedirectToAction("Details", new { id = courseId });
        }
    }
}

StudentInformationSystem/StudentInformationSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StudentInformationSystem.Models;
using System.Diagnostics;

namespace StudentInformationSystem.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        
        public async Task<IActionResult> Error(int statusCode)
        {
            if (statusCode == 400)
            {
                return View("Error400");
            }

            if (statusCode == 401)
            {
                return View("Error401");
            }

            return View();
        }
    }
}

StudentInformationSystem/StudentInformationSystem/Controllers/UniversityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentInformationSystem.Services.Contracts;
using StudentInformationSystem.Services.Services;
using StudentInformationSystem.Web.ViewModels.University;

namespace StudentInformationSystem.Controllers
{
    [Authorize]
    public class UniversityController : Controller
    {
        private readonly IUniversityService universityService;

        public UniversityController(IUniversityService universityService)
        {
            this.universityService = universityService;
        }
        public async Task<IActionResult> ShowAll()
        {
            var universities = await this.universityService.ShowAll();
            return View(universities);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            var universityCreateViewModel = new UniversityCreateViewModel();
            return View(universityCreateViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(UniversityCreateViewModel universityCreateViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(universityCreateViewModel);
            }

            await this.universityService.Create(universityCreateViewModel);
            return RedirectToAction("ShowAll");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var universityEditViewModel = await this.universityService.GetUniversityEditViewModelById(id);
            return View(universityEditViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, UniversityEditViewModel universityEditViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(universityEditViewModel);
            }

            await this.universityService.Edit(id, universityEditViewModel);
            return RedirectToAction("ShowAll");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            await this.universityService.Delete(id);
            return RedirectToAction("ShowAll");
        }
    }
}

StudentInformationSystem/StudentInformationSystem/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Manage.Internal;
using Microsoft.AspNetCore.Mvc;
using StudentInformationSystem.Services.Contracts;
using StudentInformationSystem.Web.ViewModels.User;
using StudentInfromationSystem.Data.Models;

namespace StudentInformationSystem.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public UserController(IUserService userService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userService = userService;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }                          
            
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult GiveStudentRole()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GiveStudentRole(string username)
        {
            var user = await this.userManager.FindByNameAsync(username);
            await this.userService.AddStudentToRoleAsync(user.Id);
            return RedirectToAction("All", "Student");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult GiveTeacherRole()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> GiveTeacherRole(string username)
        {
            try
            {
                var user = await this.userManager.FindByNameAsync(username);
                await this.userService.AddTeacherToRoleAsync(user.Id);
            }
            catch (Exception e)
            {
                TempData["ErrorMessage"] = "You need to enter a valid teacher username";
                return View();
            }   
            return RedirectToAction("All", "Teacher");
        }

        [HttpGet]
        public IActionResult ChangePassword(string email)
        {
            var model = new ChangePasswordViewModel();
            model.Email = email;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(string email, ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.Email = email;
                var user = await userManager.FindByNameAsync(User.Identity.Name);

                if (user != null)
                {
                    var signInResult = await signInManager.CheckPasswordSignInAsync(user, model.OldPassword, lockoutOnFailure: false);

                    if (signInResult.Succeeded)
                    {
                        var changePasswordResult = await userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);

                        if (changePasswordResult.Succeeded)
                        {
                            await this.userService.ChangeUserStatus(user);
                            await this.signInManager.SignInAsync(user, isPersistent: false);
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            foreach (var error in changePasswordResult.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Invalid old password.");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "User not found.");
                }
            }
            return View();
        }
    }
}

StudentInformationSystem/StudentInformationSystem/Views/Home/Error400.cshtml
@{
    ViewData["Title"] = "Error";
}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <br>
        <div class="row">
            <div class="col-10">
                <img src="https://assets.wpdeveloper.com/2021/12/5083c4b6-1280x720_v2.jpeg" alt="Alternative image" class="img-thumbnail">
                <div class="text-left h4">
                    <p>Oops, better check that URL. Page was not found.</p>
                </div>
                <div class="text-left h4"> Go back to <a asp-controller="Home" asp-action="Index">Home</a> Page</div>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>

StudentInformationSystem/StudentInformationSystem/Views/Home/Error401.cshtml
@{
    ViewData["Title"] = "Error";
}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <br>
        <div class="row">
            <div class="col-10">
                <img src="https://www.elegantthemes.com/blog/wp-content/uploads/2019/12/401-error-wordpress-featured-image.jpg" alt="Alternative image" class="img-thumbnail">
                <div class="text-left h4">
                    <p>Oops, you don't have access here.</p>
                </div>
                <div class="text-left h4"> Go back to <a asp-controller="Home" asp-action="Index">Home</a> Page</div>
            </div>
        </div>
    </div>
    <div class="col-3"></div>
</div>

StudentInformationSystem/StudentInformationSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Student Information System";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            font-size: 16px;
            line-height: 1.6;
        }
        .navbar {
            background-color: #343a40;
        }
        .navbar-brand {
            font-size: 24px;
        }
        .nav-link {
            font-size: 20px;
        }
        .container {
            padding: 20px;
        }
        .panel{
            margin-top: 50px;
        }

    </style>
</head>
<body>
    <div class="container mt-4">
        <h1>Welcome to the Student Information System</h1>
        <p>
            This is a simple Student Information System that allows you to manage student data efficiently. You can add, update, and delete student records, view their details, and perform various other operations.
        </p>
        <hr />

        <h3>Quick Links</h3>
        <div class="row">
            <div class="col-md-6">
                <a class="btn btn-primary btn-block" asp-controller="Student" asp-action="All">View All Students</a>
            </div>
            <div class="col-md-6">
                <a class="btn btn-success btn-block" asp-controller="Teacher" asp-action="All">View All Teachers</a>
            </div>
        </div>
        
        @if (@User.IsInRole("Admin"))
        {
            <div class="panel">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <div class="container">
                        <a class="navbar-brand" href="#">Admin Panel</a>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <ul class="navbar-nav ml-auto">
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="GiveStudentRole">Add Student to Role</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="University" asp-action="Create">Add University</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Course" asp-action="ShowAll">List All Courses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Teacher" asp-action="AddTeacher">Add Teacher</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Add">Add Student</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="User" asp-action="GiveTeacherRole">Add Teacher To Role</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Add">Add Course</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>
        }
    </div>
</body>
</html>