StudentInformationSystem/StudentInformationSystem/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudentInformationSystem.Services.Contracts;
using StudentInformationSystem.Web.ViewModels.Faculty;

namespace StudentInformationSystem.Controllers
{
    public class FacultyController : Controller
    {
        private readonly IFacultyService facultyService;
        private readonly IUniversityService universityService;

        public FacultyController(IFacultyService facultyService, IUniversityService universityService)
        {
            this.facultyService = facultyService;
            this.universityService = universityService;
        }

        [HttpGet]
        public async Task<IActionResult> ShowAllForUniversity(int id)
        {
            var faculties = await this.facultyService.ShowAllFacultiesForUniversity(id);

            return View(faculties);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add()
        {
            var specialty = new AddFacultyViewModel();
            specialty.Universities = await this.universityService.GetUniversitiesForDropDownAsync();
            return View(specialty);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add(AddFacultyViewModel model)
        {
            await this.facultyService.AddFaculty(model);
            return RedirectToAction("ShowAll", "University");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var faculty = await this.facultyService.PrepareForEditFaculty(id);
            return View(faculty);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, EditFacultyViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Invalid data.";
                model.Universities = await this.universityService.GetUniversitiesForDropDownAsync();
                return View(model);
            }
            await this.facultyService.EditFaculty(id, model);
            return RedirectToAction("ShowAll", "University");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            await this.facultyService.DeleteFaculty(id);
            return RedirectToAction("ShowAll", "University");
        }
    }
}

StudentInformationSystem/StudentInformationSystem/Controllers/SpecialtyController.cs
using Microsoft.AspNetCore.Mvc;
using StudentInformationSystem.Services.Contracts;
using StudentInformationSystem.Web.ViewModels.Speacialty;

namespace StudentInformationSystem.Controllers
{
    public class SpecialtyController : Controller
    {
        private readonly ISpecialtyService specialtyService;
        private readonly IFacultyService facultyService;

        public SpecialtyController(ISpecialtyService specialtyService, IFacultyService facultyService)
        {
            this.specialtyService = specialtyService;
            this.facultyService = facultyService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var specialty = await this.specialtyService.GetSpecialtyDetailsAsync(id);
            return View(specialty);
        }

        public async Task<IActionResult> All(int id)
        {
            var specialties = await this.specialtyService.GetSpecialtiesForFacultyAsync(id);
            return View(specialties);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var faculties = await this.facultyService.FacultiesForDropDown();
            var model = new SpecialtyAddViewModel()
            {
                Faculties = faculties
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(SpecialtyAddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.specialtyService.AddSpecialtyAsync(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await this.specialtyService.GetSpecialtyForEditAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SpecialtyEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.specialtyService.EditSpecialtyAsync(id, model);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.specialtyService.DeleteSpecialtyAsync(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

StudentInformationSystem/StudentInformationSystem/Views/Faculty/Add.cshtml
@model AddFacultyViewModel

@{
    ViewData["Title"] = "Add Faculty";
}

<h2>@ViewData["Title"]</h2>

<div id="errorAlert" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
    @TempData["ErrorMessage"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form asp-action="Add" method="post">
    <div class="form-group">
        <label>Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label>Image URL</label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="Description" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="UniversityId"></label>
        <select asp-for="UniversityId" class="form-control">
            @foreach (var university in Model.Universities)
            {
                <option value="@university.Id">@university.Name</option>
            }
        </select>
        <span asp-validation-for="UniversityId" class="small text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            var errorMessage = "@TempData["ErrorMessage"]";
            if (errorMessage) {
                $("#errorAlert").removeClass("d-none");
            }

            $(".alert .close").on("click", function () {
                $(this).parent().fadeOut(500);
            });
        });
    </script>

    <partial name="_ValidationScriptsPartial" />
}

StudentInformationSystem/StudentInformationSystem/Views/Faculty/Edit.cshtml
@model EditFacultyViewModel

@{
    ViewData["Title"] = "Add Faculty";
}

<h2>@ViewData["Title"]</h2>

<div id="errorAlert" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
    @TempData["ErrorMessage"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form asp-action="Add" method="post">
    <div class="form-group">
        <label>Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label>Image URL</label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="Description" class="small text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="UniversityId"></label>
        <select asp-for="UniversityId" class="form-control">
            @foreach (var university in Model.Universities)
            {
                <option value="@university.Id">@university.Name</option>
            }
        </select>
        <span asp-validation-for="UniversityId" class="small text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            var errorMessage = "@TempData["ErrorMessage"]";
            if (errorMessage) {
                $("#errorAlert").removeClass("d-none");
            }

            $(".alert .close").on("click", function () {
                $(this).parent().fadeOut(500);
            });
        });
    </script>

    <partial name="_ValidationScriptsPartial" />
}

StudentInformationSystem/StudentInformationSystem/Views/Faculty/ShowAllForUniversity.cshtml
@model IList<ShowAllFacultiesViewModel>

@{
    ViewData["Title"] = "Faculties";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        .carousel-inner img {
            max-width: 100%;
            height: 100%;
        }

    </style>
</head>
<body>
    <div class="container mt-4">
        <h1>@ViewData["Title"]</h1>

        <div id="facultyCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                @for (var i = 0; i < Model.Count; i++)
                {
                    <li data-target="#facultyCarousel" data-slide-to="@i" @(i == 0 ? "class='active'" : "")></li>
                }
            </ol>

            <div class="carousel-inner">
                @for (var i = 0; i < Model.Count; i++)
                {
                    <div class="carousel-item @(i == 0 ? "active" : "")">
                        <img src="@Model[i].ImageUrl" alt="Faculty Image">
                        <div class="carousel-caption">
                            <h3>@Model[i].Name</h3>
                            <p>@Model[i].Description</p>
                            <div class="btn-group">
                                <a asp-controller="Specialty" asp-action="All" asp-route-id="@Model[i].Id" class="btn btn-primary">Specialties</a>
                            
                                @if (User.IsInRole("Admin"))
                                {
                                    <a asp-controller="Faculty" asp-action="Edit" asp-route-id="@Model[i].Id" class="btn btn-warning">Edit</a>
                                    <a asp-controller="Faculty" asp-action="Delete" asp-route-id="@Model[i].Id" class="btn btn-danger">Delete</a>
                                    
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>

            <a class="carousel-control-prev" href="#facultyCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#facultyCarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</body>
</html>